# Lowering memory to 2GB to prevent the "Paging File" crash
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError

# Essential for modern Flutter apps
android.useAndroidX=true
android.enableJetifier=true

# Optional: Helps with build speed in some cases
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=true